---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11.4

inputs:
  - name: repo

run:
  path: bash
  dir: repo
  args:
    - -c
    - |
      go test -v ./...
